version: "3"
services: 
  web: 
    image: tranminhan/friendlyhello:20171112
    deploy:
      replicas: 10
      resources: 
        limits: 
          cpus: "0.1"
          memory: 50MB
      restart_policy:
        condition: on-failure
    ports:
      - "80:80"
    networks: 
      - webnet
networks: 
  webnet: